DROP TABLE IF EXISTS laptops CASCADE;
DROP TABLE IF EXISTS ads CASCADE;
DROP TABLE IF EXISTS laptop_images CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS user_favorites CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS chats CASCADE;
DROP TABLE IF EXISTS chat_members CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(225) NOT NULL,
  email VARCHAR(225) NOT NULL,
  password VARCHAR (225) NOT NULL,
  contact_phone VARCHAR(15) NOT NULL,
  photo_url VARCHAR(2000),
  is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE laptops (
  id SERIAL PRIMARY KEY NOT NULL,
  brand_name VARCHAR(225) NOT NULL,
  screen_size NUMERIC NOT NULL DEFAULT 0,
  condition VARCHAR(225) NOT NULL,
  memory INTEGER NOT NULL DEFAULT 0,
  price NUMERIC NOT NULL DEFAULT 0,
  storage_size NUMERIC NOT NULL DEFAULT 0,
  storage_type VARCHAR(225) NOT NULL
);

CREATE TABLE laptop_images (
  id SERIAL PRIMARY KEY NOT NULL,
  laptop_id INTEGER REFERENCES laptops(id) ON DELETE CASCADE,
  url VARCHAR(225) NOT NULL,
  created_at DATE NOT NULL,
  updated_at DATE NOT NULL
);

CREATE TABLE ads (
  id SERIAL PRIMARY KEY NOT NULL,
  laptop_id INTEGER REFERENCES laptops(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(225) NOT NULL,
  description TEXT,
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(225),
  created_at DATE NOT NULL,
  updated_at DATE NOT NULL,
  laptop_image_id INTEGER REFERENCES laptop_images(id) ON DELETE CASCADE
);

CREATE TABLE user_favorites (
  id SERIAL PRIMARY KEY NOT NULL,
  ad_id INTEGER REFERENCES ads(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  created_at DATE NOT NULL,
  updated_at DATE NOT NULL
);

CREATE TABLE chats (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(225) NOT NULL,
  created_at DATE NOT NULL,
  updated_at DATE NOT NULL
);

CREATE TABLE messages (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE,
  body TEXT,
  created_at DATE NOT NULL,
  updated_at DATE NOT NULL
);

CREATE TABLE chat_members (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  chat_id INTEGER REFERENCES chats(id) ON DELETE CASCADE
);
